spring:
  application:
    name: spring_9jwt
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    # 실습 1. 윈도우 설치한 오라클 서버(다른 컴퓨터로 접속)
    url: jdbc:oracle:thin:@//192.168.0.253:1521/xe
    username: c##idev
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        '[format_sql]': true
    defer-datasource-initialization: true        
logging:
  level:
    '[org.iclass.spring_9jwt]': DEBUG
    '[org.springframework.security]': DEBUG
  pattern:
    console: '%clr(%-5level){yellow} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n'
springdoc:
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
  api-docs: 
    enabled: true
server:
  port: 8080    
# http://localhost:8080/swagger-ui/index.html
# http://localhost:8080/v3/api-docs(OpenAPI JSON 문서)

